title: CV | Jithin Johny
description:  A beautiful template for your CV.
url: https://jithinjohny86.github.io/jithinjohny1.github.io/
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
